project_id = "pyupvlgdtcxgqjungiof"

[functions.get-availability]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.send-instructor-summary]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.generate-giftcard-pdf]
verify_jwt = false

[functions.send-session-codes-email]
verify_jwt = false

[functions.get-giftcard-data]
verify_jwt = false

[functions.purchase-session-package]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.send-session-feedback]
verify_jwt = false

[functions.send-abandonment-email]
verify_jwt = false

[functions.facebook-conversions]
verify_jwt = false

[functions.mailerlite-init-shop]
verify_jwt = false

[functions.mailerlite-sync-order]
verify_jwt = false

[functions.book-trial-class]
verify_jwt = false
