project_id = "pyupvlgdtcxgqjungiof"

[functions.get-availability]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.generate-giftcard-pdf]
verify_jwt = false

[functions.send-session-codes-email]
verify_jwt = false
